version: "3"

services:
  # --- MySQLi
  #
  mysql:
    container_name: "mysql"
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=12345
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=12345
    ports:
      - '3306:3306'
    volumes:
      - ./docker/mysql/data:/bitnami/mysql/data
  # --- PHP 7.4
  #
  php:
    container_name: "php"
    image: bitnami/php-fpm:7.4
    volumes:
      - ./docker/www:/app:delegated
      - ./docker/php/php.ini:/opt/bitnami/php/etc/conf.d/php.ini:ro
  # --- Apache 2.4
  #
  apache:
    container_name: "apache"
    image: bitnami/apache:2.4
    ports:
      - '80:8080'
      - '443:8443'
    depends_on:
      - php
    volumes:
      - ./docker/www:/app:delegated
      - ./docker/apache/my_vhost.conf:/vhosts/myapp.conf:ro
      - ./docker/apache/certs:/certs
  # --- PhpMyAdmin latest
  # Acccess via
  # https://127.0.0.1:8143
  # Login with user root and mysql-password.
  #
  phpmyadmin:
    container_name: "phpmyadmin"
    image: bitnami/phpmyadmin:latest
    depends_on:
      - mysql
    ports:
      - '8143:8443'
    environment:
      - DATABASE_HOST=host.docker.internal
volumes:
  mysql:
    driver: local